version: '3.11'

services:
  bot:
    build:
      context: .
    volumes:
      - .:/code
      - sqlite_data:/code/db  
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000 &
        python3 bot.py
      "

volumes:
  sqlite_data:
